version: '3'
services:
        web:
                image: flask_aliya
                build: .
                ports:
                        - "8089:8080"
                volumes:
                        - persistent_volume:/app/volumes
volumes:
  persistent_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/Flask-Python-Aliya/volumes
